### ISSUE TITLE
page not showing up

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#194]
https://csumb.edu/compliance/contact-questions-answers

**Comment by kevee** [comment]
Fixed per https://github.com/csumb/web-content/commit/87de314f2c5d3c389a4fce4d117eecdac9057fc9

**Comment by thburns** [comment]
@kevee you fixed this 17 hours ago. https://csumb.edu/compliance/contact-questions-answers is still not showing up.

**Comment by kevee** [comment]
This was a duped page, fixed old one. https://github.com/csumb/web-content/commit/db526818e0da7232dab85e50adba353a675f9e70
